= Threads in the JVM

Threads in the JVM are represented by the https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/Thread.html[`Thread` class].

A JVM application can have multiple _application_ threads, i.e. threads running application code, in addition to the threads the JVM uses internally.

Since Java 21, there are two types of threads:

- The old _platform threads_, implemented directly by the underlying operating system (i.e. the platform). The creation, suspension, and scheduling of platform threads is delegated by the JVM into the operation system. Is is common to state that there is a 1-1 relation between a platform thread and an operation system thread.

- _virtual threads_ are implemented directly by the JVM. Namely, the creation, suspension, and scheduling of virtual threads is done directly by the JVM. 

Both platform and virtual threads are represented by the `Thread` type.

There are two common ways to directly create a thread:

- Instantiate a `Thread` instance, passing in a https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/Runnable.html[`Runnable`] instance defining the code the thread will execute. A `Runnable` is a java standard interface with a single `run` method, without arguments, returning `void`, and that doesn't throw any checked exceptions.
This method always create platform threads. 

- Use the https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/Thread.Builder.html[`Thread.Builder` interface] to create and start both platform or virtual threads. Creation of builder instances is achievable by the `Thread.ofPlatform` and `Thread.ofVirtual` static methods.

It is also possible to create `Thread` derived classes and override the https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/Thread.html#run()[`run`]. Create an instance of the derived class will result in the creation of a platform thread, which will execute the code defined in the `run` method.

Create threads remain in the https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/Thread.State.html#NEW[`NEW`], meaning that they are not ready to run.
To transition a thread into the https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/Thread.State.html#RUNNABLE[`RUNNABLE`] state, call the https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/Thread.html#start[`start`] method.
Don't mixup the `start` and `run` methods:

- The `start` method is called to transition a thread into the `RUNNING` state.
- The `run` method defines the code the thread will execute.

== Daemon threads

Threads in the JVM are divided in two types: _normal_ threads and _deamon_ threads.
This type only has influence in the JVM termination: the JVM will end if all _normal_ threads already have https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/Thread.State.html#TERMINATED[terminated], even if there are _daemon_ threads still in a non-https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/Thread.State.html#TERMINATED[`TERMINATED`] state.

When the JVM starts, multiple threads can be created automatically, however only the _main_ thread is non-daemon, i.e. the thread where the `main` method will run.
All other automatically created threads are _daemon_ threads.
When a thread is created it will have the same _daemon_ state as the thread that created it.
This means that all threads created by the main thread will be non-daemon by default, however this property can be changed after a thread is created and before it is started.

Virtual threads are always of the daemon type. Only platform types can be configured to be daemon or non-daemon.

== Thread name

Threads can be associated to names, which may be useful for debugging and monitoring purposes.
Platform threads will get an automatically generated distinct name, if one is not provided explicitly assigned.
Virtual threads have the empty string as the default name.

== Thread interruption

Thread _interruption_ is a mechanism made available by the JVM to provide support for _cancellation_.
It is a way for a thread `T1` to inform another one thread `T2` that the computation being performed by `T2` should not continue.

Consider an Android application where the reaction to an UI event triggers a network communication with an external system.
This I/O operation can potentially block and therefore cannot be made on the UI thread, so a different thread needs to be used.
If in the meanwhile the user leaves the Android activity, we probably want to cancel the pending I/O operation and thread interruption is a way to do it.

Note that an interruption will not transition the target thread to the `TERMINATED` state.
Instead it is just a mechanism to convey a cancellation request.
It is up to the interrupted thread to define what is the reaction to this request.

Threads could use a *properly synchronized* shared boolean for this task:

- The code executing in the target thread would observe this shared boolean periodically and check if it is set.
- An external thread would set this boolean to true as a way to cancel the operation in the target thread.

However threads can block, meaning that during that time they are unable to observe the shared boolean.
The interruption mechanism is therefore a way to terminate blocking method calls, by having these calls end with the throwing of the https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/InterruptedException.html[`InterruptedException`].

There are some important aspects to note regarding thread interruption:

- An `InterruptedException` will only be thrown on *some* blocking methods (marked with `throws InterruptedException`). For instance, if a thread is performing a CPU-bound operation and is interrupted, then the `InterruptedException` is not automatically thrown. Checked exceptions cannot occur out of thin air. However the exception request will be memorized and an exception will be thrown the next time the target threads does a call to a blocking operation.

- Threads can always check the _interruption status_ by calling the `isInterrupted` getter method. For instance, a thread performing a CPU-bound operation can periodically check this property to verify if a cancellation was requested.

- When creating custom synchronizers that have blocking operations, we will want to have the same behavior as the built-in synchronizers, namely we will want these blocking operations to be interruption-aware. This will introduce some challenges when designing these synchronizers, as we will see.

== Thread termination synchronization

It is possible to wait for the termination of a thread by calling the `join` instance method.
This is a potentially blocking method and therefore can throw `InterruptedException`.

== Deprecated methods

The `Thread` methods `suspend`, `resume`, and `stop` are currently deprecated and should/must no be used.
See the reasons why [here](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/doc-files/threadPrimitiveDeprecation.html).